### ISSUE TITLE
Automatic announcement addresses

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/fsd#17]
I thought this might be valuable as a config option to have it automatically compute the announcement addresses, in addition to the manual array.

You can see what I have done at https://github.com/LumeWeb/portal-plugin-ipfs/blob/ee574256baca31afc3eb6a0b354df30c6aef02af/internal/protocol/ipfs/node.go#L303

**Comment by n8maninger** [comment]
We will probably not add this. `fsd` is designed to be run as infrastructure where choices like this are better to be explicit.

**Comment by n8maninger** [comment]
@pcfreak30 speaking of which, any reason not to import the ipfs package from here. It looks like that file is a copy-paste of an older version with some minor additions. A wrapper would have gotten you the same effect with less maintenance overhead.

**Comment by pcfreak30** [comment]
> @pcfreak30 speaking of which -- any reason not to import the ipfs package from here? It looks like that file is a copy-paste of an older version with some minor additions. A wrapper would have gotten you the same effect with less maintenance overhead.

I may adapt in the future, but at the time, it was not obvious how things would turn out in design.
